# Generated by Django 2.2.10 on 2020-04-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendlouser',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
    ]
