# Generated by Django 2.2.10 on 2020-04-04 20:17

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200404_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendlouser',
            name='identifier',
            field=models.CharField(help_text='Your unique identifier on Calendlo', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='identifier can only have alphanumeric and _', regex=re.compile('^\\w+$'))]),
        ),
    ]
