# Generated by Django 2.2.10 on 2020-04-04 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200404_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendlouser',
            name='email',
            field=models.EmailField(max_length=128, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
