# Generated by Django 2.2.10 on 2020-04-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200404_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendlouser',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
    ]
