# Generated by Django 2.2.10 on 2020-04-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200406_0518'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calendlouser',
            table='calendlo_user',
        ),
    ]
