# Generated by Django 2.2.10 on 2020-04-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_auto_20200404_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityslot',
            name='end_time',
        ),
    ]
