# Generated by Django 2.2.10 on 2020-04-10 10:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('availability', '0004_auto_20200407_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availabilityslot',
            unique_together={('date', 'start_time', 'user')},
        ),
    ]
