# Generated by Django 2.2.10 on 2020-04-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointment_appointer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='calendlo_appointment',
        ),
    ]
