# Generated by Django 2.2.10 on 2020-04-05 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import libs.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('availability', '0002_auto_20200404_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(validators=[libs.validators.validate_absolute_hour])),
                ('end_time', models.TimeField(validators=[libs.validators.validate_absolute_hour])),
                ('title', models.CharField(max_length=128)),
                ('appointee_name', models.CharField(max_length=128)),
                ('appointee_email', models.EmailField(max_length=128)),
                ('description', models.TextField()),
                ('appointer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='availability.AvailabilitySlot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
