# Generated by Django 2.2.10 on 2020-04-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200406_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointer',
        ),
    ]
