# Generated by Django 2.2.10 on 2020-04-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_remove_availabilityslot_end_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availabilityslot',
            unique_together={('date', 'start_time')},
        ),
        migrations.AlterModelTable(
            name='availabilityslot',
            table='calendlo_availability_slot',
        ),
    ]
